language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
before_install:
  - sudo apt-get install libhdf5-serial-dev proj-bin libproj-dev libgeos-dev libspatialindex-dev 

install:
  - pip install cython
  - pip install .
  - pip install coveralls sphinx sphinx_rtd_theme

# command to run tests
script:
  - coverage run --rcfile=.coveragerc --source deflex -m py.test
  - coverage report

after_success:
  - coveralls
