language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

# command to install dependencies
addons:
  apt:
    packages:
      - coinor-cbc
      - libhdf5-serial-dev
      - proj-bin
      - libproj-dev
      - libgeos-dev
      - libspatialindex-dev

install:
  - pip install cython
  - pip install .
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls
