language: python

matrix:
  include:
    - python: 3.6
    - python: 3.8

# install os dependencies
addons:
  apt:
    packages:
      - coinor-cbc
      - libhdf5-serial-dev
      - proj-bin
      - libproj-dev
      - libgeos-dev
      - libspatialindex-dev
      - graphviz

# install python dependencies
install:
  - pip install cython
  - pip install .[plot]
  - pip install coveralls pytest-cov

# command to run tests
script:
  - coverage run --rcfile=.coveragerc --source deflex -m py.test
  - coverage report

after_success:
  - coveralls
